### ISSUE TITLE
UserAuth

### ISSUE THREAD

**Issue by JaredDjour** [JaredDjour/InstaDjour#5]

**Comment by JaredDjour** [comment]
Sign up, login, and demo-login (05/29/2019, 2 days)

Users can sign up, login and logout
Users can browse the site through a demo-login
Users can only use the site’s features if they are logged in

**Comment by pvulakh** [comment]
Good job finishing this up! Some changes to make: 
- [ ] Your components look small. Compare them to instagram's and make them bigger! Please center them on your page as well. 
- [ ] Remove the download from appstore/google play links from your splash since they're links to download the real instagram and not your app!
- [ ] Consider a better choose better main font since the Times New Roman (InstaDjour) doesn't look like Instagram's
- [ ] Rendered error text should be the same as Instagram's (look at what Instagram tells you when you signup/login with blank info/incorrect credentials!)
- [ ] For the sign up form, when fields are blank/invalid a red x pops up. Add this in!
- [ ] Capitalize text in footer
- [ ] Splash is separate from the signup component. Users should be able to access signup form outside of splash too
